apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: debezium-stag-idp-document
  labels:
    strimzi.io/cluster: intemo-staging-microservice-connect-cluster
spec:
  class: io.debezium.connector.postgresql.PostgresConnector
  tasksMax: 1
  config:
    database.hostname: "k8s-default-idppostg-b085acd0fd-5356e5348d2e9407.elb.ap-south-1.amazonaws.com"
    database.port: "5432"
    database.user: "postgresadmin"
    database.password: "admin123"
    database.dbname: intemo_staging
    database.server.name: idpevent
    topic.prefix: idpevent
    table.include.list: public.document_new
    plugin.name: pgoutput
    topic.creation.default.replication.factor: -1
    topic.creation.default.partitions: 1
    slot.name : "documentidpstag"