apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: staging-metrics-intemo-kafka-cluster
spec:
  kafka:
    version: 3.5.0
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
    storage:
        type: persistent-claim
        size: 8Gi
    resources:
      requests:
        cpu: 70m
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 2Gi
    resources:
      requests:
        cpu: 30m
        
  entityOperator:
    topicOperator:
      resources:
        requests:
          cpu: 150m
          memory: 128Mi
        limits:
          cpu: 350m
          memory: 256Mi