apiVersion: v1
kind: Service
metadata:
  name: mail-frontend-service
  namespace: default
  labels:
    app: staging-mail-frontend-service
  annotations:
spec:
  selector:
    app: staging-mail-frontend-app
  ports:
  - name: tcp
    port: 80
    targetPort: 80
  type: NodePort